<div class="alert alert-block alert-info" align="center" style="padding: 10px;">
<h1><b><u>MySql</u></b></h1>
</div>

#### **Q1. What is a database? Differentiate between SQL and NoSQL databases.** ####

**DATABASE:**
A database is a collection of data that is organized and stored in a way that enables efficient retrieval and manipulation of the data.

SQL and NoSQL are two different types of database management systems:

- SQL (Structured Query Language) databases are based on a relational model, where data is organized into tables with defined columns and relationships between them.

- NoSQL (Not Only SQL) databases use a variety of non-relational models, including document-based, key-value, and graph-based models. NoSQL databases are designed to be highly scalable and flexible.

---

#### **Q2. What is DDL? Explain why CREATE, DROP, ALTER, and TRUNCATE are used with an example.** ####

DDL stands for Data Definition Language, a subset of SQL used to define and manage database structures and objects. Examples of DDL statements and their uses:

- `CREATE`: Used to create new database objects, such as tables, views, indexes, and constraints.

- `DROP`: Used to delete existing database objects, such as tables, views, indexes, and constraints.

- `ALTER`: Used to modify existing database objects, such as tables, views, indexes, and constraints.

- `TRUNCATE`: Used to delete all data from a table, keeping its structure and indexes intact.

---

#### **Q3. What is DML? Explain INSERT, UPDATE, and DELETE with an example.** ####

DML stands for Data Manipulation Language, a subset of SQL used to insert, update, and delete data in a database. Examples of DML statements and their uses:

- `INSERT`: Used to add new rows of data to a table.

- `UPDATE`: Used to modify existing rows of data in a table.

- `DELETE`: Used to remove rows of data from a table.

---

#### **Q4. What is DQL? Explain SELECT with an example.** ####

DQL stands for Data Query Language, a subset of SQL (Structured Query Language) used to retrieve data from a database. DQL statements are used to select data from one or more tables in a database and can be used to perform complex queries to retrieve specific data.

The SELECT statement is used to retrieve data from a database. Some examples of a SELECT statement:

```sql
SELECT * FROM customers;
SELECT name, email FROM customers;
SELECT name, email FROM customers WHERE age > 18;

```
---

#### **Q5. Explain Primary Key and Foreign Key.** ####

**PRIMARY KEY:**
A primary key is a column or set of columns in a table that uniquely identifies each row in that table. The primary key must be unique, meaning that no two rows can have the same values in the primary key column(s). Additionally, the primary key column(s) cannot contain null values.

**FOREIGN KEY:**
A foreign key is a column or set of columns in a table that refers to the primary key of another table. It creates a relationship between two tables based on the values in the columns. The foreign key column(s) in one table must have values that match the values of the primary key column(s) in the other table. This creates a link between the two tables and allows data to be retrieved from both tables at the same time.

---

#### **Q6. Write a Python code to connect MySQL to Python. Explain the cursor() and execute() method.** ####

```python
import mysql.connector
mydb = mysql.connector.connect(
  host="localhost",
  user="abc",
  password="password",
  database="test"
)
mycursor = mydb.cursor()
mycursor.execute("SELECT * FROM test_table")
for row in mycursor.fetchall():
    print(row)

```    
The cursor() method creates a cursor object that allows us to execute SQL statements and fetch results, while the execute() method is used to execute a SQL statement.

---

#### **Q7. Give the order of execution of SQL clauses in an SQL query.** ####

The order of execution of SQL clauses in an SQL query is as follows:

- `FROM` - Specifies the table to retrieve data from.
- `WHERE` - Filters the rows to be retrieved based on the specified conditions.
- `GROUP BY` - Groups the rows based on one or more columns.
- `HAVING` - Filters the groups based on the specified conditions.
- `SELECT` - Retrieves the specified columns for the rows that satisfy the conditions.
- `ORDER BY` - Sorts the rows based on the specified columns and sort order.